### ISSUE TITLE
Go 1.6: panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by AkihiroSuda** [osrg/earthquake#119]
This should be https://github.com/golang/go/issues/14210.

```
$ sudo EQ_DEBUG=1 ./bin/earthquake inspectors ethernet -autopilot ~/WORK/ether.toml -nfq-number 42
..
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
        panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0xbf6fc0, 0xc8211b9d00)
        /home/suda/go/src/runtime/panic.go:464 +0x3e6
github.com/osrg/earthquake/earthquake/util/core.Recoverer()
        /home/suda/gopath/src/github.com/osrg/earthquake/earthquake/util/core/coreutil.go:50 +0x106
panic(0xbf6fc0, 0xc8211b9d00)
        /home/suda/go/src/runtime/panic.go:426 +0x4e9
github.com/AkihiroSuda/go-netfilter-queue._cgoCheckPointer0(0xa8c7e0, 0xc8211abe58, 0xc8211b9cf0, 0x1, 0x1, 0xa4d380)
        github.com/AkihiroSuda/go-netfilter-queue/_obj/_cgo_gotypes.go:59 +0x4d
github.com/AkihiroSuda/go-netfilter-queue.NewNFQueue(0x100013a002a, 0xffff, 0xdd0b60, 0x0, 0x0)
        /home/suda/gopath/src/github.com/AkihiroSuda/go-netfilter-queue/netfilter.go:101 +0x47a
github.com/osrg/earthquake/earthquake/inspector/ethernet.(*NFQInspector).Serve(0xc8200e1600, 0x0, 0x0)
        /home/suda/gopath/src/github.com/osrg/earthquake/earthquake/inspector/ethernet/ethernet_nfq.go:53 +0x2c4
github.com/osrg/earthquake/earthquake/cli/inspectors.runEtherInspector(0xc82000a180, 0x4, 0x4, 0x1)
        /home/suda/gopath/src/github.com/osrg/earthquake/earthquake/cli/inspectors/ethernet.go:125 +0x903
github.com/osrg/earthquake/earthquake/cli/inspectors.etherCmd.Run(0xc82000a180, 0x4, 0x4, 0xc8211d1b30)
        /home/suda/gopath/src/github.com/osrg/earthquake/earthquake/cli/inspectors/ethernet.go:62 +0x35
github.com/osrg/earthquake/earthquake/cli/inspectors.(*etherCmd).Run(0x18f20e8, 0xc82000a180, 0x4, 0x4, 0xeaaec0)
        <autogenerated>:2 +0xab
github.com/mitchellh/cli.(*CLI).Run(0xc8211b63c0, 0xc8211af2c0, 0x0, 0x0)
        /home/suda/gopath/src/github.com/mitchellh/cli/cli.go:153 +0x56e
github.com/osrg/earthquake/earthquake/cli.inspectorsCmd.Run(0xc82000a170, 0x5, 0x5, 0xc8211d1d28)
        /home/suda/gopath/src/github.com/osrg/earthquake/earthquake/cli/inspectors.go:51 +0x1f2
github.com/osrg/earthquake/earthquake/cli.(*inspectorsCmd).Run(0x18f20e8, 0xc82000a170, 0x5, 0x5, 0xeaaea8)
        <autogenerated>:5 +0xab
github.com/mitchellh/cli.(*CLI).Run(0xc8211b6300, 0xc8211af170, 0x0, 0x0)
        /home/suda/gopath/src/github.com/mitchellh/cli/cli.go:153 +0x56e
github.com/osrg/earthquake/earthquake/cli.CLIMain(0xc82000a150, 0x7, 0x7, 0x0)
        /home/suda/gopath/src/github.com/osrg/earthquake/earthquake/cli/main.go:36 +0x2d6
main.main()
        /home/suda/gopath/src/github.com/osrg/earthquake/earthquake/main.go:25 +0x3b

```

**Comment by AkihiroSuda** [comment]
Fixed in https://github.com/AkihiroSuda/go-netfilter-queue/pull/1
